### ISSUE TITLE
[#0302] Criar layout para cadastro de estações e seus sensores

### ISSUE THREAD

**Issue by MariaGabrielaReis** [The-Bugger-Ducks/cloud-fox-front#1]
## Sobre a Tarefa

Desenhar fluxo de cadastro de estações e seus sensores (sugestão: home → cadastro de estações → home)

> Levar em consideração os dados disponíveis para armazenamento, conforme resultado desta task: [BACK #01](https://github.com/The-Bugger-Ducks/cloud-fox-back/issues/1)

#### Definition of Ready
- [x] Critério de aceite
- [x] Cabe em uma sprint (de preferência não maior que 8 story points)
- [x] Detalhes de acesso (que perfil pode acessar o que nesta tarefa)

#### Definition of Done
- [x] Atende aos critérios de aceite
- [x] Documentado
- [x] Aceito pelo PO

#### Critérios de aceitação: 
- [x] O fluxo para o cadastro de estações e sensores deve ser simples
- [x] A experiência do usuário deve ser garantida
- [x] O usuário deve saber onde está e poderá cancelar a operação a qualquer momento
- [x] O layout deve ser pensado para usuário gerenciador de estação

**Comment by gioliveirass** [comment]
# Documentação

## Descrição

Após discussão do grupo em sala de aula, foi definido que o "Cadastro de estações" no front-end será, na realidade, "Ativação de estações". O motivo da decisão é que as estações devem ser previamente cadastradas no back-end, de forma que a ação do usuário no front é somente adicionar informações (nome, descrição e endereço) a uma estação já existente. Dessa forma, irá evitar que o usuário cadastre uma estação que não existe, gerando algum tipo de bug.

Também foi definido que não haverá cadastro de sensores, e que serão exibidas automaticamente todas as informações disponíveis da estação.

## Tecnologias utilizadas

Somente o Figma foi utilizado para prototipação

## Tela

A tela de ativação de estações corresponde a um modal que aparecerá sobre a homepage.
![Image](https://user-images.githubusercontent.com/78885451/189884440-a65a2fcc-350d-4426-9c92-0f0c27f94c21.png)

**Comment by ThHenrique** [comment]
Aprovado
