### ISSUE TITLE
[#0701] Criar layout para login de usuários

### ISSUE THREAD

**Issue by MariaGabrielaReis** [The-Bugger-Ducks/cloud-fox-front#11]
## Sobre a Tarefa

Desenhar fluxo de login de usuários (sugestão: home → login OU cadastro → home logada)

> Levar em consideração os dados disponíveis para armazenamento, conforme resultado desta task: [BACK #07](https://github.com/The-Bugger-Ducks/cloud-fox-back/issues/7)

#### Definition of Ready
- [x] Critério de aceite
- [x] Cabe em uma sprint (de preferência não maior que 8 story points)
- [x] Detalhes de acesso (que perfil pode acessar o que nesta tarefa)

#### Definition of Done
- [x] Atende aos critérios de aceite
- [x] Documentado
- [x] Aceito pelo PO

#### Critérios de aceitação: 
- [x] Deverá contém opção para utilizar OAuth2
- [x] A experiência do usuário deve ser garantida
- [x] O layout deve ser pensado para usuário comuns

**Comment by gioliveirass** [comment]
De acordo com o que foi solicitado pelo PO, o login deve ser somente com a utilização OAuth. Portanto, foram adicionadas as opções de login com as seguintes mídias sociais:

- Google;
- Facebook;
- Apple.

Para essa tela, foi utilizado um design limpo que buscasse deixar somente o necessário no foco do usuário: as opções de login. Os botões de login não fugiram dos padrões encontrados em demais locais da internet para as mídias sociais em questão - ou seja, foram preservadas as logos e as colorações que remetem as midias de forma que não cause estranheza para os usuários.

O resultado final obtido na prototipação da tela de login/cadastro utilizando a ferramenta Figma foi:

![Image](https://user-images.githubusercontent.com/78885451/187568386-dcd78bdf-5bbc-419e-b783-302f17c0965b.png)
