### ISSUE TITLE
[#0707] Consumir lib para aplicação de login social com “OAuth2”

### ISSUE THREAD

**Issue by MariaGabrielaReis** [The-Bugger-Ducks/cloud-fox-front#14]
## Sobre a Tarefa

Consumir biblioteca para utilização de login social (sugestão: [AWS - Cognito](https://aws.amazon.com/pt/cognito/) e [OAuth2](https://developers.google.com/identity/protocols/oauth2) )

#### Definition of Ready
- [x] Critério de aceite
- [x] Cabe em uma sprint (de preferência não maior que 8 story points)
- [x] Detalhes de acesso (que perfil pode acessar o que nesta tarefa)
- [x] Endpoints a serem utilizadas
- [x] Protótipo

#### Definition of Done
- [x] Testado e integrado
- [x] Sem bugs observados / review
- [x] Code review
- [x] Atende aos critérios de aceite
- [ ] Documentado
- [x] Aceito pelo PO

#### Critérios de aceitação: 
- [x] Tratar SQL injection dos inputs
- [x] Tratar possíveis erros
- [x] Notificar usuário (caso erro, ou, sucesso)

**Comment by ThHenrique** [comment]
# Documentação

### Descrição
Tela para login de usuários

### Tecnologias
React e Styled Components

## Telas
![image](https://user-images.githubusercontent.com/69374340/190426595-8386d4bd-d354-4004-a2f3-14b3ed2d45ce.png)
