### ISSUE TITLE
[#0601] Criar layout para pedir para atualizar nível do perfil e lista de aceite (admin)

### ISSUE THREAD

**Issue by MariaGabrielaReis** [The-Bugger-Ducks/cloud-fox-front#17]
## Sobre a Tarefa

Desenhar fluxo de edição de usuários tanto da visão usuário comum, que solicita a permissão, como para o administradorm que concede a permissão.

#### Definition of Ready
- [x] Critério de aceite
- [x] Cabe em uma sprint (de preferência não maior que 8 story points)
- [x] Detalhes de acesso (que perfil pode acessar o que nesta tarefa)

#### Definition of Done
- [x] Atende aos critérios de aceite
- [x] Documentado
- [x] Aceito pelo PO

#### Critérios de aceitação: 
- [x] O fluxo para o administrador conceder privilégio para usuários deve ser simples
- [x] O usuário deverá saber o que é um gerenciador de estação
- [x] A experiência do usuário deve ser garantida
- [x] O usuário deve saber onde está e poderá cancelar a operação a qualquer momento
- [x] O layout deve ser pensado para usuário comuns

**Comment by gioliveirass** [comment]
# Documentação

## Descrição

Qualquer perfil logado pode acessar essa tela.

## Tecnologias

Somente o Figma foi utilizado para prototipação.

## Tela

A tela de solicitação de atualização de nível do perfil é conjunta com a tela de perfil do usuário.

![Image](https://user-images.githubusercontent.com/78885451/189886887-486618af-deb3-4507-ba2d-3f0b77ce0303.png)

**Comment by ThHenrique** [comment]
gradientes lindos demaissss, muito bom. Validado
