### ISSUE TITLE
[#0801] Criar layout para exclusão de conta

### ISSUE THREAD

**Issue by MariaGabrielaReis** [The-Bugger-Ducks/cloud-fox-front#20]
## Sobre a Tarefa

Desenhar fluxo de exclusão de conta do usuário (sugestão: home → perfil → modal (?) de excluir conta → home)

#### Definition of Ready
- [x] Critério de aceite
- [x] Cabe em uma sprint (de preferência não maior que 8 story points)
- [x] Detalhes de acesso (que perfil pode acessar o que nesta tarefa)

#### Definition of Done 
- [x] Atende aos critérios de aceite
- [x] Documentado
- [x] Aceito pelo PO

#### Critérios de aceitação: 
- [x] O fluxo para o exclusão de conta deve ser simples
- [x] A experiência do usuário deve ser garantida
- [x] O usuário deve saber onde está e poderá cancelar a operação a qualquer momento
- [x] O layout deve ser pensado para usuário comuns

**Comment by gioliveirass** [comment]
# Documentação

## Descrição

A opção de exclusão de conta fica localizada na tela "Meu perfil". Ao clicar na opção, um modal de confirmação aparecerá, garantindo assim que o usuário esteja ciente do que está fazendo e tenha a oportunidade de cancelar sua ação.

## Tecnologias

Somente o Figma foi utilizado na documentação.

## Telas

Botão de exclusão de conta na tela "Meu perfil":

![Image](https://user-images.githubusercontent.com/78885451/189889457-06a346e4-cf24-40f8-afd6-7282bd0a3df6.png)

Confirmação de exclusão da conta:

![Image](https://user-images.githubusercontent.com/78885451/189888910-2f597b0f-0437-447d-bb51-5748c373a7a7.png)

**Comment by ThHenrique** [comment]
Gostei da seta, aprovado
