### ISSUE TITLE
[#1001] Criar layout do dashboard para visualização dos parâmetros meteorológicos

### ISSUE THREAD

**Issue by MariaGabrielaReis** [The-Bugger-Ducks/cloud-fox-front#23]
## Sobre a Tarefa

Desenhar tela de dashboard com a visualização dos parâmetros meteorológicos

> Levar em consideração os dados disponíveis sobre estações, resultado desta task: [BACK #01](https://github.com/The-Bugger-Ducks/cloud-fox-back/issues/1)

#### Definition of Ready
- [x] Critério de aceite
- [x] Cabe em uma sprint (de preferência não maior que 8 story points)
- [x] Detalhes de acesso (que perfil pode acessar o que nesta tarefa)

#### Definition of Done
- [x] Atende aos critérios de aceite
- [x] Documentado
- [x] Aceito pelo PO

#### Critérios de aceitação: 
- [x] A dashboard com a visualização dos parâmetros meteorológicos deverá ser simples
- [x] A experiência do usuário deve ser garantida
- [x] O layout deve ser pensado para usuário comuns

**Comment by gioliveirass** [comment]
# Documentação

## Descrição

Qualquer usuário pode acessar o dashboard, porém apenas usuário logados podem acessar a opção de filtrar informações dos gráficos.

## Tecnologias

Somente o Figma foi utilizado para a prototipação.

## Telas

Dashboard:

![Image](https://user-images.githubusercontent.com/78885451/189885622-dd43e422-b315-4dc8-a378-3885305b1576.png)

Modal de filtragem:

![Image](https://user-images.githubusercontent.com/78885451/189885897-96b3128f-a060-48b4-b28b-afae97a0f8f8.png)

**Comment by ThHenrique** [comment]
Aprovado
