### ISSUE TITLE
[#1004] Criar interface para o dashboard de visualização dos parâmetros meteorológicos

### ISSUE THREAD

**Issue by MariaGabrielaReis** [The-Bugger-Ducks/cloud-fox-front#24]
## Sobre a Tarefa

Criar tela de dashboard para visualização dos parâmetros meteorológicos

> Conforme definido no layout resultado desta task: [FRONT #23](https://github.com/The-Bugger-Ducks/cloud-fox-front/issues/23)

#### Definition of Ready
- [x] Critério de aceite
- [x] Cabe em uma sprint (de preferência não maior que 8 story points)
- [x] Detalhes de acesso (que perfil pode acessar o que nesta tarefa)
- [x] Endpoints a serem utilizadas
- [x] Protótipo

#### Definition of Done
- [x] Testado e integrado
- [x] Sem bugs observados / review
- [x] Code review
- [x] Atende aos critérios de aceite
- [x] Documentado
- [x] Aceito pelo PO

#### Critérios de aceitação: 
- [x] Atende ao protótipo desenvolvido

**Comment by gioliveirass** [comment]
# Documentação

## Descrição

Página estática seguindo o potótipo do Dashboard. A página contém os dados meteorológicos apresentados em gráficos. Os dados apresentados serão fictícios até o consumo da rota para obtê-los estar pronta.

## Tecnologias

React, styled-components e Highcharts para os gráficos.

## Telas

Obs: Foi necessário aumentar o tamanho do card em comparação ao protótipo para ele caber e ficar bonito.
![Image](https://user-images.githubusercontent.com/78885451/190474224-4b51851f-23d8-4d64-bc75-9bc6db9f1ffb.png)
