### ISSUE TITLE
Criar layout para homepage

### ISSUE THREAD

**Issue by MariaGabrielaReis** [The-Bugger-Ducks/cloud-fox-front#27]
## Sobre a Tarefa

Desenhar tela de homepage

#### Definition of Ready
- [x] Critério de aceite
- [x] Cabe em uma sprint (de preferência não maior que 8 story points)
- [x] Detalhes de acesso (que perfil pode acessar o que nesta tarefa)

#### Definition of Done 
- [x] Atende aos critérios de aceite
- [x] Documentado
- [x] Aceito pelo PO

#### Critérios de aceitação: 
- [x] A experiência do usuário deve ser garantida
- [x] O layout deve ser pensado para usuário comuns

**Comment by ThHenrique** [comment]
Muito linda 🥰 aprovado
