### ISSUE TITLE
Criar interface para homepage

### ISSUE THREAD

**Issue by MariaGabrielaReis** [The-Bugger-Ducks/cloud-fox-front#28]
## Sobre a Tarefa

Criar tela de homepage

> Conforme definido no layout resultado desta task: [FRONT #27](https://github.com/The-Bugger-Ducks/cloud-fox-front/issues/27)

#### Definition of Ready
- [x] Critério de aceite
- [x] Cabe em uma sprint (de preferência não maior que 8 story points)
- [x] Detalhes de acesso (que perfil pode acessar o que nesta tarefa)
- [x] Endpoints a serem utilizadas
- [x] Protótipo

#### Definition of Done
- [x] Testado e integrado
- [x] Sem bugs observados / review
- [x] Code review
- [x] Atende aos critérios de aceite
- [x] Documentado
- [x] Aceito pelo PO

#### Critérios de aceitação: 
- [x] Atende ao protótipo desenvolvido

**Comment by gioliveirass** [comment]
# Documentação

## Descrição

Página homepage onde serão ativadas e exibidas novas estações.

## Tecnologias

React e styled-components.

## Telas

![Image](https://user-images.githubusercontent.com/78885451/190838572-aee88917-7485-42ad-a1dd-860f1432a131.png)
