### ISSUE TITLE
[#0501] Criar layout para listagem de usuários (para admin mudar permissão de usuários)

### ISSUE THREAD

**Issue by MariaGabrielaReis** [The-Bugger-Ducks/cloud-fox-front#29]
## Sobre a Tarefa

Layout de listagem de usuários para atualização de nível de permissão/privilégio.

#### Definition of Ready
- [x] Critério de aceite
- [x] Cabe em uma sprint (de preferência não maior que 8 story points)
- [x] Detalhes de acesso (que perfil pode acessar o que nesta tarefa)

#### Definition of Done
- [x] Atende aos critérios de aceite
- [x] Documentado
- [x] Aceito pelo PO

#### Critérios de aceitação: 
- [x] A experiência do usuário deve ser garantida
- [x] O layout deve ser pensado para usuário leigos

**Comment by gioliveirass** [comment]
# Documentação

## Descrição

Tela para gerenciamento de usuários. A tela só ficará disponível para usuários administradores, e permitirá que os mesmos tenham um controle sobre o nível de permissão de todos os usuários.

## Tecnologias

Somente o Figma foi utilizado para prototipação.

## Telas

![Image](https://user-images.githubusercontent.com/78885451/189891598-66c3bc67-0ca7-4fd6-b8fb-1e74c425cea7.png)

**Comment by ThHenrique** [comment]
Shoow, aprovado!
