### ISSUE TITLE
[#0607] Criar layout para aceitar/recusar pedido de troca de perfil (administrador)

### ISSUE THREAD

**Issue by MariaGabrielaReis** [The-Bugger-Ducks/cloud-fox-front#30]
## Sobre a Tarefa

Desenhar fluxo de aceite ou rejeito de pedidos de troca de perfil (ação do administrador).

#### Definition of Ready
- [x] Critério de aceite
- [x] Cabe em uma sprint (de preferência não maior que 8 story points)
- [x] Detalhes de acesso (que perfil pode acessar o que nesta tarefa)

#### Definition of Done
- [x] Atende aos critérios de aceite
- [x] Documentado
- [x] Aceito pelo PO

#### Critérios de aceitação:
- [x] A experiência do usuário deve ser garantida
- [x] O layout deve ser pensado para usuário leigos

**Comment by gioliveirass** [comment]
# Documentação

## Descrição

A tela listará todas as solicitações de atualização de nível de perfil/privilégio feitas por usuários. O administrador é o único com acesso a essa tela, e poderá recusar ou aceitar cada solicitação.

## Tecnologias

Somente o Figma foi utilizado para prototipação.

## Telas

![Image](https://user-images.githubusercontent.com/78885451/189892651-1feebfca-457a-4225-9f70-6276e144213c.png)

**Comment by ThHenrique** [comment]
Aprovado
