### ISSUE TITLE
Design System (cores, tipografia, componentes)

### ISSUE THREAD

**Issue by MariaGabrielaReis** [The-Bugger-Ducks/cloud-fox-front#4]
## Sobre a Tarefa

Levantar design system (cores, tipografia, componentes) para padronização e harmonia da plataforma

#### Definition of Ready 
- [x] Critério de aceite
- [x] Cabe em uma sprint (de preferência não maior que 8 story points)

#### Definition of Done 
- [x] Atende aos critérios de aceite
- [x] Documentado
- [x] Aceito pelo PO

#### Critérios de aceitação: 
- [x] Tipografia
- [x] Paleta de cores
- [x] Exemplos

**Comment by ThHenrique** [comment]
@gioliveirass  anexado a task

[Design_System.pdf](https://github.com/The-Bugger-Ducks/cloud-fox-front/files/9448404/Design_System.pdf)
